version: "3.6"
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: redirect_example_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./index.php:/app/index.php:ro
    ports:
      - 127.0.0.1:8080:8080

  php:
    image: php:8.2-fpm-alpine3.19
    container_name: redirect_example_php
    volumes:
      - ./index.php:/app/index.php:ro

  app:
    build: ../
    container_name: redirect_app
    environment:
      LISTEN_PORT: 8090
      REDIS_HOST: redis:6379
      PROXY_MODE: true
    ports:
      - 127.0.0.1:8090:8090
    cap_drop:
      - ALL

  redis:
   image: redis
   container_name: redirect_redis
