name: Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create container
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: redirect-manager
          tags: latest
          registry: ghcr.io
          dockerfile: Dockerfile
